// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package games.model.dummy;

import games.model.dummy.Dummy;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Dummy_Roo_Configurable {
    
    declare @type: Dummy: @Configurable;
    
}
