// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package games.model.dummy;

import games.model.dummy.Dummy;

privileged aspect Dummy_Roo_JavaBean {
    
    public String Dummy.getName() {
        return this.name;
    }
    
    public void Dummy.setName(String name) {
        this.name = name;
    }
    
}
